version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos_app_laravel
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pos_db_laravel
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local
